name=Kali's Content Expansion
desc=Alpha 4
# Set this to True only if your mod customizes anything that is loaded before starting a game, like the main menu or loading screens.
author=KaliDitzy
requires reload=True
tags = Textures, Sounds, Models, Rooms, Items, SCP-294 Drinks, Loading Screens
